### ISSUE TITLE
BUG No JS module 'tweener' found in search path

### ISSUE THREAD

**Issue by mbousq** [gnome-hub/gnomehub_extension#39]
**Describe the bug**
I can sucessfully install the extension but not load it.
I got the error "No JS module 'tweener' found in search path"

**How do we reproduce the bug*
1. install
2. enable extension

**Desktop (please complete the following information):**
neofetch

OS: Ubuntu 21.10 x86_64 
Kernel: 5.13.0-39-generic 
GNOME 40.5 
WM: Mutter 

**Extras**
Found some info about this :)
https://askubuntu.com/questions/1286212/no-js-module-tweener-found-in-search-path-gnome-shell-extension-error-on-ubun

https://gitlab.com/jenslody/gnome-shell-extension-panel-osd/-/merge_requests/30?commit_id=00890e56fc3c172369ccb3e06bb411386ae58bd5

Looking forward trying this extension, really looks cool ! Thanks

**Comment by Colton-K** [comment]
Thank you for pointing this out! I believe this pull request fixes the issue, let us know if it doesn't.
