### ISSUE TITLE
BUG - Weather widget is not updating

### ISSUE THREAD

**Issue by varora24** [gnome-hub/gnomehub_extension#42]
**Describe the bug**
The weather information does not update live and is still showing the same information as it did when I installed it.

**How do we reproduce the bug*
1. Install the extension
2. Notice the weather the next day or at night -> It does not update
**Expected behavior**
The latest weather and weather icon should be shown 

**Desktop (please complete the following information):**
-  OS:  Ubuntu
-  OS Version : 21.10
-  Gnome Desktop Version: 40.5

**Comment by Colton-K** [comment]
Should be fixed!
